### PR TITLE
Converted to jsx3

### PR DESCRIPTION
**Pull request by xavierzwirtz**
Converted to the new zero cost bindings in `reason-react`.

### CODE REVIEW

**Comment by mscharley** [comment]
I'll have to check this offline since you did the rebuild as part of the same commit as the actual changes. This sounds like a great addition though so thanks in advance!

**Comment by mscharley** [comment]
What version of reason-react brought in this new style of binding? I'll need to bump the package.json to require at least that version.

**Comment by xavierzwirtz** [comment]
[0.7.0](https://reasonml.github.io/reason-react/blog/2019/04/10/react-hooks)

**Comment by mscharley** [comment]
I'm guessing based on the way this has changed that the simple functor for adding new icons is not possible either, hey? That's a shame. I'll review and get this out this weekend.

**Comment by xavierzwirtz** [comment]
From my experimentation no, it is not. However this style of binding brings support for zero cost bindings.

**Comment by mscharley** [comment]
Note to self: This needs the README to be updated after it's merged.

**Comment by mscharley** [comment]
@xavierzwirtz Let me know if 1.0.1 works well for you. 1.0.0 had a packaging glitch and won't work. 

3cbae7e9709e20769a90fe7c505dd412e49e568b

**Comment by xavierzwirtz** [comment]
Everything looks great. Thanks for getting this released.

**Pull request merged**
